development: &development
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: owc
  password: owc123
  database: owc_development

test: &test
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: owc
  password: owc123
  database: owc_test

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
